/*
 * Decompiled with CFR 0_110.
 */
package ec.com.atikasoft.proteus.expr.function;

import java.util.HashMap;
import java.util.Map;
import ec.com.atikasoft.proteus.expr.Expr;
import ec.com.atikasoft.proteus.expr.ExprException;
import ec.com.atikasoft.proteus.expr.ExprFunction;
import ec.com.atikasoft.proteus.expr.IEvaluationContext;
import ec.com.atikasoft.proteus.expr.IExprFunction;
import ec.com.atikasoft.proteus.expr.function.IFunctionProvider;
import ec.com.atikasoft.proteus.expr.function.excel.ABS;
import ec.com.atikasoft.proteus.expr.function.excel.ACOS;
import ec.com.atikasoft.proteus.expr.function.excel.ACOSH;
import ec.com.atikasoft.proteus.expr.function.excel.ADDMONTH;
import ec.com.atikasoft.proteus.expr.function.excel.ADDRESS;
import ec.com.atikasoft.proteus.expr.function.excel.ADDYEAR;
import ec.com.atikasoft.proteus.expr.function.excel.AND;
import ec.com.atikasoft.proteus.expr.function.excel.AREAS;
import ec.com.atikasoft.proteus.expr.function.excel.ASIN;
import ec.com.atikasoft.proteus.expr.function.excel.ASINH;
import ec.com.atikasoft.proteus.expr.function.excel.ATAN;
import ec.com.atikasoft.proteus.expr.function.excel.ATAN2;
import ec.com.atikasoft.proteus.expr.function.excel.ATANH;
import ec.com.atikasoft.proteus.expr.function.excel.AVEDEV;
import ec.com.atikasoft.proteus.expr.function.excel.AVERAGE;
import ec.com.atikasoft.proteus.expr.function.excel.AVERAGEA;
import ec.com.atikasoft.proteus.expr.function.excel.BAHTTEXT;
import ec.com.atikasoft.proteus.expr.function.excel.BETADIST;
import ec.com.atikasoft.proteus.expr.function.excel.BETAINV;
import ec.com.atikasoft.proteus.expr.function.excel.BINOMDIST;
import ec.com.atikasoft.proteus.expr.function.excel.CEILING;
import ec.com.atikasoft.proteus.expr.function.excel.CELL;
import ec.com.atikasoft.proteus.expr.function.excel.CHAR;
import ec.com.atikasoft.proteus.expr.function.excel.CHIDIST;
import ec.com.atikasoft.proteus.expr.function.excel.CHIINV;
import ec.com.atikasoft.proteus.expr.function.excel.CHITEST;
import ec.com.atikasoft.proteus.expr.function.excel.CHOOSE;
import ec.com.atikasoft.proteus.expr.function.excel.CLEAN;
import ec.com.atikasoft.proteus.expr.function.excel.CODE;
import ec.com.atikasoft.proteus.expr.function.excel.COLUMN;
import ec.com.atikasoft.proteus.expr.function.excel.COLUMNS;
import ec.com.atikasoft.proteus.expr.function.excel.COMBIN;
import ec.com.atikasoft.proteus.expr.function.excel.CONCATENATE;
import ec.com.atikasoft.proteus.expr.function.excel.CONFIDENCE;
import ec.com.atikasoft.proteus.expr.function.excel.CORREL;
import ec.com.atikasoft.proteus.expr.function.excel.COS;
import ec.com.atikasoft.proteus.expr.function.excel.COSH;
import ec.com.atikasoft.proteus.expr.function.excel.COUNT;
import ec.com.atikasoft.proteus.expr.function.excel.COUNTA;
import ec.com.atikasoft.proteus.expr.function.excel.COUNTBLANK;
import ec.com.atikasoft.proteus.expr.function.excel.COUNTIF;
import ec.com.atikasoft.proteus.expr.function.excel.COVAR;
import ec.com.atikasoft.proteus.expr.function.excel.CRITBINOM;
import ec.com.atikasoft.proteus.expr.function.excel.DATE;
import ec.com.atikasoft.proteus.expr.function.excel.DATEVALUE;
import ec.com.atikasoft.proteus.expr.function.excel.DAVERAGE;
import ec.com.atikasoft.proteus.expr.function.excel.DAY;
import ec.com.atikasoft.proteus.expr.function.excel.DAYS360;
import ec.com.atikasoft.proteus.expr.function.excel.DB;
import ec.com.atikasoft.proteus.expr.function.excel.DCOUNT;
import ec.com.atikasoft.proteus.expr.function.excel.DCOUNTA;
import ec.com.atikasoft.proteus.expr.function.excel.DDB;
import ec.com.atikasoft.proteus.expr.function.excel.DEGREES;
import ec.com.atikasoft.proteus.expr.function.excel.DEVSQ;
import ec.com.atikasoft.proteus.expr.function.excel.DGET;
import ec.com.atikasoft.proteus.expr.function.excel.DMAX;
import ec.com.atikasoft.proteus.expr.function.excel.DMIN;
import ec.com.atikasoft.proteus.expr.function.excel.DOLLAR;
import ec.com.atikasoft.proteus.expr.function.excel.DPRODUCT;
import ec.com.atikasoft.proteus.expr.function.excel.DSTDEV;
import ec.com.atikasoft.proteus.expr.function.excel.DSTDEVP;
import ec.com.atikasoft.proteus.expr.function.excel.DSUM;
import ec.com.atikasoft.proteus.expr.function.excel.DVAR;
import ec.com.atikasoft.proteus.expr.function.excel.DVARP;
import ec.com.atikasoft.proteus.expr.function.excel.ERRORTYPE;
import ec.com.atikasoft.proteus.expr.function.excel.EVEN;
import ec.com.atikasoft.proteus.expr.function.excel.EXACT;
import ec.com.atikasoft.proteus.expr.function.excel.EXP;
import ec.com.atikasoft.proteus.expr.function.excel.EXPONDIST;
import ec.com.atikasoft.proteus.expr.function.excel.FACT;
import ec.com.atikasoft.proteus.expr.function.excel.FALSE;
import ec.com.atikasoft.proteus.expr.function.excel.FDIST;
import ec.com.atikasoft.proteus.expr.function.excel.FIND;
import ec.com.atikasoft.proteus.expr.function.excel.FINV;
import ec.com.atikasoft.proteus.expr.function.excel.FISHER;
import ec.com.atikasoft.proteus.expr.function.excel.FISHERNV;
import ec.com.atikasoft.proteus.expr.function.excel.FIXED;
import ec.com.atikasoft.proteus.expr.function.excel.FLOOR;
import ec.com.atikasoft.proteus.expr.function.excel.FORECAST;
import ec.com.atikasoft.proteus.expr.function.excel.FREQUENCY;
import ec.com.atikasoft.proteus.expr.function.excel.FTEST;
import ec.com.atikasoft.proteus.expr.function.excel.FV;
import ec.com.atikasoft.proteus.expr.function.excel.GAMMADIST;
import ec.com.atikasoft.proteus.expr.function.excel.GAMMAINV;
import ec.com.atikasoft.proteus.expr.function.excel.GAMMALN;
import ec.com.atikasoft.proteus.expr.function.excel.GEOMEAN;
import ec.com.atikasoft.proteus.expr.function.excel.GETPIVOTDATA;
import ec.com.atikasoft.proteus.expr.function.excel.GROWTH;
import ec.com.atikasoft.proteus.expr.function.excel.HARMEAN;
import ec.com.atikasoft.proteus.expr.function.excel.HLOOKUP;
import ec.com.atikasoft.proteus.expr.function.excel.HOUR;
import ec.com.atikasoft.proteus.expr.function.excel.HYPERLINK;
import ec.com.atikasoft.proteus.expr.function.excel.HYPGEOMDIST;
import ec.com.atikasoft.proteus.expr.function.excel.IF;
import ec.com.atikasoft.proteus.expr.function.excel.INDEX;
import ec.com.atikasoft.proteus.expr.function.excel.INDIRECT;
import ec.com.atikasoft.proteus.expr.function.excel.INFO;
import ec.com.atikasoft.proteus.expr.function.excel.INT;
import ec.com.atikasoft.proteus.expr.function.excel.INTERCEPT;
import ec.com.atikasoft.proteus.expr.function.excel.IPMT;
import ec.com.atikasoft.proteus.expr.function.excel.IRR;
import ec.com.atikasoft.proteus.expr.function.excel.ISBLANK;
import ec.com.atikasoft.proteus.expr.function.excel.ISERR;
import ec.com.atikasoft.proteus.expr.function.excel.ISLOGICAL;
import ec.com.atikasoft.proteus.expr.function.excel.ISNA;
import ec.com.atikasoft.proteus.expr.function.excel.ISNONTEXT;
import ec.com.atikasoft.proteus.expr.function.excel.ISNUMBER;
import ec.com.atikasoft.proteus.expr.function.excel.ISPMT;
import ec.com.atikasoft.proteus.expr.function.excel.ISREF;
import ec.com.atikasoft.proteus.expr.function.excel.ISTEXT;
import ec.com.atikasoft.proteus.expr.function.excel.KURT;
import ec.com.atikasoft.proteus.expr.function.excel.LARGE;
import ec.com.atikasoft.proteus.expr.function.excel.LEFT;
import ec.com.atikasoft.proteus.expr.function.excel.LEN;
import ec.com.atikasoft.proteus.expr.function.excel.LINEST;
import ec.com.atikasoft.proteus.expr.function.excel.LN;
import ec.com.atikasoft.proteus.expr.function.excel.LOG;
import ec.com.atikasoft.proteus.expr.function.excel.LOG10;
import ec.com.atikasoft.proteus.expr.function.excel.LOGEST;
import ec.com.atikasoft.proteus.expr.function.excel.LOGINV;
import ec.com.atikasoft.proteus.expr.function.excel.LOGNORMDIST;
import ec.com.atikasoft.proteus.expr.function.excel.LOOKUP;
import ec.com.atikasoft.proteus.expr.function.excel.LOWER;
import ec.com.atikasoft.proteus.expr.function.excel.MATCH;
import ec.com.atikasoft.proteus.expr.function.excel.MAX;
import ec.com.atikasoft.proteus.expr.function.excel.MAXA;
import ec.com.atikasoft.proteus.expr.function.excel.MDETERM;
import ec.com.atikasoft.proteus.expr.function.excel.MEDIAN;
import ec.com.atikasoft.proteus.expr.function.excel.MID;
import ec.com.atikasoft.proteus.expr.function.excel.MIN;
import ec.com.atikasoft.proteus.expr.function.excel.MINA;
import ec.com.atikasoft.proteus.expr.function.excel.MINUTE;
import ec.com.atikasoft.proteus.expr.function.excel.MINVERSE;
import ec.com.atikasoft.proteus.expr.function.excel.MIRR;
import ec.com.atikasoft.proteus.expr.function.excel.MMULT;
import ec.com.atikasoft.proteus.expr.function.excel.MOD;
import ec.com.atikasoft.proteus.expr.function.excel.MODE;
import ec.com.atikasoft.proteus.expr.function.excel.MONTH;
import ec.com.atikasoft.proteus.expr.function.excel.N;
import ec.com.atikasoft.proteus.expr.function.excel.NA;
import ec.com.atikasoft.proteus.expr.function.excel.NEGBINOMDIST;
import ec.com.atikasoft.proteus.expr.function.excel.NORMDIST;
import ec.com.atikasoft.proteus.expr.function.excel.NORMINV;
import ec.com.atikasoft.proteus.expr.function.excel.NORMSDIST;
import ec.com.atikasoft.proteus.expr.function.excel.NORMSINV;
import ec.com.atikasoft.proteus.expr.function.excel.NOT;
import ec.com.atikasoft.proteus.expr.function.excel.NOW;
import ec.com.atikasoft.proteus.expr.function.excel.NPER;
import ec.com.atikasoft.proteus.expr.function.excel.NPV;
import ec.com.atikasoft.proteus.expr.function.excel.ODD;
import ec.com.atikasoft.proteus.expr.function.excel.OFFSET;
import ec.com.atikasoft.proteus.expr.function.excel.OR;
import ec.com.atikasoft.proteus.expr.function.excel.PEARSON;
import ec.com.atikasoft.proteus.expr.function.excel.PERCENTILE;
import ec.com.atikasoft.proteus.expr.function.excel.PERCENTRANK;
import ec.com.atikasoft.proteus.expr.function.excel.PERMUT;
import ec.com.atikasoft.proteus.expr.function.excel.PI;
import ec.com.atikasoft.proteus.expr.function.excel.PMT;
import ec.com.atikasoft.proteus.expr.function.excel.POISSON;
import ec.com.atikasoft.proteus.expr.function.excel.POWER;
import ec.com.atikasoft.proteus.expr.function.excel.PPMT;
import ec.com.atikasoft.proteus.expr.function.excel.PROB;
import ec.com.atikasoft.proteus.expr.function.excel.PRODUCT;
import ec.com.atikasoft.proteus.expr.function.excel.PROPER;
import ec.com.atikasoft.proteus.expr.function.excel.PV;
import ec.com.atikasoft.proteus.expr.function.excel.QUARTILE;
import ec.com.atikasoft.proteus.expr.function.excel.RADIANS;
import ec.com.atikasoft.proteus.expr.function.excel.RAND;
import ec.com.atikasoft.proteus.expr.function.excel.RANK;
import ec.com.atikasoft.proteus.expr.function.excel.RATE;
import ec.com.atikasoft.proteus.expr.function.excel.REPLACE;
import ec.com.atikasoft.proteus.expr.function.excel.REPT;
import ec.com.atikasoft.proteus.expr.function.excel.RIGHT;
import ec.com.atikasoft.proteus.expr.function.excel.ROMAN;
import ec.com.atikasoft.proteus.expr.function.excel.ROUND;
import ec.com.atikasoft.proteus.expr.function.excel.ROUNDDOWN;
import ec.com.atikasoft.proteus.expr.function.excel.ROUNDUP;
import ec.com.atikasoft.proteus.expr.function.excel.ROW;
import ec.com.atikasoft.proteus.expr.function.excel.ROWS;
import ec.com.atikasoft.proteus.expr.function.excel.RSQ;
import ec.com.atikasoft.proteus.expr.function.excel.RTD;
import ec.com.atikasoft.proteus.expr.function.excel.SEARCH;
import ec.com.atikasoft.proteus.expr.function.excel.SECOND;
import ec.com.atikasoft.proteus.expr.function.excel.SIGN;
import ec.com.atikasoft.proteus.expr.function.excel.SIN;
import ec.com.atikasoft.proteus.expr.function.excel.SINH;
import ec.com.atikasoft.proteus.expr.function.excel.SKEW;
import ec.com.atikasoft.proteus.expr.function.excel.SLN;
import ec.com.atikasoft.proteus.expr.function.excel.SLOPE;
import ec.com.atikasoft.proteus.expr.function.excel.SMALL;
import ec.com.atikasoft.proteus.expr.function.excel.SQRT;
import ec.com.atikasoft.proteus.expr.function.excel.STANDARDIZE;
import ec.com.atikasoft.proteus.expr.function.excel.STDEV;
import ec.com.atikasoft.proteus.expr.function.excel.STDEVA;
import ec.com.atikasoft.proteus.expr.function.excel.STDEVP;
import ec.com.atikasoft.proteus.expr.function.excel.STDEVPA;
import ec.com.atikasoft.proteus.expr.function.excel.STEYX;
import ec.com.atikasoft.proteus.expr.function.excel.SUBSTITUTE;
import ec.com.atikasoft.proteus.expr.function.excel.SUBTOTAL;
import ec.com.atikasoft.proteus.expr.function.excel.SUM;
import ec.com.atikasoft.proteus.expr.function.excel.SUMIF;
import ec.com.atikasoft.proteus.expr.function.excel.SUMPRODUCT;
import ec.com.atikasoft.proteus.expr.function.excel.SUMSQ;
import ec.com.atikasoft.proteus.expr.function.excel.SUMX2MY2;
import ec.com.atikasoft.proteus.expr.function.excel.SUMX2PY2;
import ec.com.atikasoft.proteus.expr.function.excel.SUMXMY2;
import ec.com.atikasoft.proteus.expr.function.excel.SYD;
import ec.com.atikasoft.proteus.expr.function.excel.T;
import ec.com.atikasoft.proteus.expr.function.excel.TAN;
import ec.com.atikasoft.proteus.expr.function.excel.TANH;
import ec.com.atikasoft.proteus.expr.function.excel.TDIST;
import ec.com.atikasoft.proteus.expr.function.excel.TEXT;
import ec.com.atikasoft.proteus.expr.function.excel.TIME;
import ec.com.atikasoft.proteus.expr.function.excel.TIMEVALUE;
import ec.com.atikasoft.proteus.expr.function.excel.TINV;
import ec.com.atikasoft.proteus.expr.function.excel.TODAY;
import ec.com.atikasoft.proteus.expr.function.excel.TRANSPOSE;
import ec.com.atikasoft.proteus.expr.function.excel.TREND;
import ec.com.atikasoft.proteus.expr.function.excel.TRIM;
import ec.com.atikasoft.proteus.expr.function.excel.TRIMMEAN;
import ec.com.atikasoft.proteus.expr.function.excel.TRUE;
import ec.com.atikasoft.proteus.expr.function.excel.TRUNC;
import ec.com.atikasoft.proteus.expr.function.excel.TTEST;
import ec.com.atikasoft.proteus.expr.function.excel.TYPE;
import ec.com.atikasoft.proteus.expr.function.excel.UPPER;
import ec.com.atikasoft.proteus.expr.function.excel.VALUE;
import ec.com.atikasoft.proteus.expr.function.excel.VAR;
import ec.com.atikasoft.proteus.expr.function.excel.VARA;
import ec.com.atikasoft.proteus.expr.function.excel.VARP;
import ec.com.atikasoft.proteus.expr.function.excel.VARPA;
import ec.com.atikasoft.proteus.expr.function.excel.VDB;
import ec.com.atikasoft.proteus.expr.function.excel.VLOOKUP;
import ec.com.atikasoft.proteus.expr.function.excel.WEEKDAY;
import ec.com.atikasoft.proteus.expr.function.excel.WEIBULL;
import ec.com.atikasoft.proteus.expr.function.excel.YEAR;
import ec.com.atikasoft.proteus.expr.function.excel.ZTEST;

public class ExcelFunctionProvider
        implements IFunctionProvider {

    private static Map<String, IExprFunction> functions = new HashMap<String, IExprFunction>();

    @Override
    public boolean hasFunction(ExprFunction function) {
        return functions.containsKey(function.getName().toUpperCase());
    }

    @Override
    public Expr evaluate(IEvaluationContext context, ExprFunction function) throws ExprException {
        IExprFunction f = functions.get(function.getName().toUpperCase());
        if (f != null) {
            return f.evaluate(context, function.getArgs());
        }
        return null;
    }

    static {
        functions.put("ABS", new ABS());
        functions.put("ACOS", new ACOS());
        functions.put("ACOSH", new ACOSH());
        functions.put("ADDRESS", new ADDRESS());
        functions.put("AND", new AND());
        functions.put("AREAS", new AREAS());
        functions.put("ASIN", new ASIN());
        functions.put("ASINH", new ASINH());
        functions.put("ATAN", new ATAN());
        functions.put("ATAN2", new ATAN2());
        functions.put("ATANH", new ATANH());
        functions.put("AVEDEV", new AVEDEV());
        functions.put("AVERAGE", new AVERAGE());
        functions.put("AVERAGEA", new AVERAGEA());
        functions.put("BAHTTEXT", new BAHTTEXT());
        functions.put("BETADIST", new BETADIST());
        functions.put("BETAINV", new BETAINV());
        functions.put("BINOMDIST", new BINOMDIST());
        functions.put("CEILING", new CEILING());
        functions.put("CELL", new CELL());
        functions.put("CHAR", new CHAR());
        functions.put("CHIDIST", new CHIDIST());
        functions.put("CHIINV", new CHIINV());
        functions.put("CHITEST", new CHITEST());
        functions.put("CHOOSE", new CHOOSE());
        functions.put("CLEAN", new CLEAN());
        functions.put("CODE", new CODE());
        functions.put("COLUMN", new COLUMN());
        functions.put("COLUMNS", new COLUMNS());
        functions.put("COMBIN", new COMBIN());
        functions.put("CONCATENATE", new CONCATENATE());
        functions.put("CONFIDENCE", new CONFIDENCE());
        functions.put("CORREL", new CORREL());
        functions.put("COS", new COS());
        functions.put("COSH", new COSH());
        functions.put("COUNT", new COUNT());
        functions.put("COUNTA", new COUNTA());
        functions.put("COUNTBLANK", new COUNTBLANK());
        functions.put("COUNTIF", new COUNTIF());
        functions.put("COVAR", new COVAR());
        functions.put("CRITBINOM", new CRITBINOM());
        functions.put("DATE", new DATE());
        functions.put("DATEVALUE", new DATEVALUE());
        functions.put("DAVERAGE", new DAVERAGE());
        functions.put("DAY", new DAY());
        functions.put("DAYS360", new DAYS360());
        functions.put("DB", new DB());
        functions.put("DCOUNT", new DCOUNT());
        functions.put("DCOUNTA", new DCOUNTA());
        functions.put("DDB", new DDB());
        functions.put("DEGREES", new DEGREES());
        functions.put("DEVSQ", new DEVSQ());
        functions.put("DGET", new DGET());
        functions.put("DMAX", new DMAX());
        functions.put("DMIN", new DMIN());
        functions.put("DOLLAR", new DOLLAR());
        functions.put("DPRODUCT", new DPRODUCT());
        functions.put("DSTDEV", new DSTDEV());
        functions.put("DSTDEVP", new DSTDEVP());
        functions.put("DSUM", new DSUM());
        functions.put("DVAR", new DVAR());
        functions.put("DVARP", new DVARP());
        functions.put("ERROR.TYPE", new ERRORTYPE());
        functions.put("EVEN", new EVEN());
        functions.put("EXACT", new EXACT());
        functions.put("EXP", new EXP());
        functions.put("EXPONDIST", new EXPONDIST());
        functions.put("FACT", new FACT());
        functions.put("FALSE", new FALSE());
        functions.put("FDIST", new FDIST());
        functions.put("FIND", new FIND());
        functions.put("FINV", new FINV());
        functions.put("FISHER", new FISHER());
        functions.put("FISHERNV", new FISHERNV());
        functions.put("FIXED", new FIXED());
        functions.put("FLOOR", new FLOOR());
        functions.put("FORECAST", new FORECAST());
        functions.put("FREQUENCY", new FREQUENCY());
        functions.put("FTEST", new FTEST());
        functions.put("FV", new FV());
        functions.put("GAMMADIST", new GAMMADIST());
        functions.put("GAMMAINV", new GAMMAINV());
        functions.put("GAMMALN", new GAMMALN());
        functions.put("GEOMEAN", new GEOMEAN());
        functions.put("GETPIVOTDATA", new GETPIVOTDATA());
        functions.put("GROWTH", new GROWTH());
        functions.put("HARMEAN", new HARMEAN());
        functions.put("HLOOKUP", new HLOOKUP());
        functions.put("HOUR", new HOUR());
        functions.put("HYPERLINK", new HYPERLINK());
        functions.put("HYPGEOMDIST", new HYPGEOMDIST());
        functions.put("IF", new IF());
        functions.put("INDEX", new INDEX());
        functions.put("INDIRECT", new INDIRECT());
        functions.put("INFO", new INFO());
        functions.put("INT", new INT());
        functions.put("INTERCEPT", new INTERCEPT());
        functions.put("IPMT", new IPMT());
        functions.put("IRR", new IRR());
        functions.put("ISBLANK", new ISBLANK());
        functions.put("ISERR", new ISERR());
        functions.put("ISLOGICAL", new ISLOGICAL());
        functions.put("ISNA", new ISNA());
        functions.put("ISNONTEXT", new ISNONTEXT());
        functions.put("ISNUMBER", new ISNUMBER());
        functions.put("ISPMT", new ISPMT());
        functions.put("ISREF", new ISREF());
        functions.put("ISTEXT", new ISTEXT());
        functions.put("KURT", new KURT());
        functions.put("LARGE", new LARGE());
        functions.put("LEFT", new LEFT());
        functions.put("LEN", new LEN());
        functions.put("LINEST", new LINEST());
        functions.put("LN", new LN());
        functions.put("LOG", new LOG());
        functions.put("LOG10", new LOG10());
        functions.put("LOGEST", new LOGEST());
        functions.put("LOGINV", new LOGINV());
        functions.put("LOGNORMDIST", new LOGNORMDIST());
        functions.put("LOOKUP", new LOOKUP());
        functions.put("LOWER", new LOWER());
        functions.put("MATCH", new MATCH());
        functions.put("MAX", new MAX());
        functions.put("MAXA", new MAXA());
        functions.put("MDETERM", new MDETERM());
        functions.put("MEDIAN", new MEDIAN());
        functions.put("MID", new MID());
        functions.put("MIN", new MIN());
        functions.put("MINA", new MINA());
        functions.put("MINUTE", new MINUTE());
        functions.put("MINVERSE", new MINVERSE());
        functions.put("MIRR", new MIRR());
        functions.put("MMULT", new MMULT());
        functions.put("MOD", new MOD());
        functions.put("MODE", new MODE());
        functions.put("MONTH", new MONTH());
        functions.put("N", new N());
        functions.put("NA", new NA());
        functions.put("NEGBINOMDIST", new NEGBINOMDIST());
        functions.put("NORMDIST", new NORMDIST());
        functions.put("NORMINV", new NORMINV());
        functions.put("NORMSDIST", new NORMSDIST());
        functions.put("NORMSINV", new NORMSINV());
        functions.put("NOT", new NOT());
        functions.put("NOW", new NOW());
        functions.put("NPER", new NPER());
        functions.put("NPV", new NPV());
        functions.put("ODD", new ODD());
        functions.put("OFFSET", new OFFSET());
        functions.put("OR", new OR());
        functions.put("PEARSON", new PEARSON());
        functions.put("PERCENTILE", new PERCENTILE());
        functions.put("PERCENTRANK", new PERCENTRANK());
        functions.put("PERMUT", new PERMUT());
        functions.put("PI", new PI());
        functions.put("PMT", new PMT());
        functions.put("POISSON", new POISSON());
        functions.put("POWER", new POWER());
        functions.put("PPMT", new PPMT());
        functions.put("PROB", new PROB());
        functions.put("PRODUCT", new PRODUCT());
        functions.put("PROPER", new PROPER());
        functions.put("PV", new PV());
        functions.put("QUARTILE", new QUARTILE());
        functions.put("RADIANS", new RADIANS());
        functions.put("RAND", new RAND());
        functions.put("RANK", new RANK());
        functions.put("RATE", new RATE());
        functions.put("REPLACE", new REPLACE());
        functions.put("REPT", new REPT());
        functions.put("RIGHT", new RIGHT());
        functions.put("ROMAN", new ROMAN());
        functions.put("ROUND", new ROUND());
        functions.put("ROUNDDOWN", new ROUNDDOWN());
        functions.put("ROUNDUP", new ROUNDUP());
        functions.put("ROW", new ROW());
        functions.put("ROWS", new ROWS());
        functions.put("RSQ", new RSQ());
        functions.put("RTD", new RTD());
        functions.put("SEARCH", new SEARCH());
        functions.put("SECOND", new SECOND());
        functions.put("SIGN", new SIGN());
        functions.put("SIN", new SIN());
        functions.put("SINH", new SINH());
        functions.put("SKEW", new SKEW());
        functions.put("SLN", new SLN());
        functions.put("SLOPE", new SLOPE());
        functions.put("SMALL", new SMALL());
        functions.put("SQRT", new SQRT());
        functions.put("STANDARDIZE", new STANDARDIZE());
        functions.put("STDEV", new STDEV());
        functions.put("STDEVA", new STDEVA());
        functions.put("STDEVP", new STDEVP());
        functions.put("STDEVPA", new STDEVPA());
        functions.put("STEYX", new STEYX());
        functions.put("SUBSTITUTE", new SUBSTITUTE());
        functions.put("SUBTOTAL", new SUBTOTAL());
        functions.put("SUM", new SUM());
        functions.put("SUMIF", new SUMIF());
        functions.put("SUMPRODUCT", new SUMPRODUCT());
        functions.put("SUMSQ", new SUMSQ());
        functions.put("SUMX2MY2", new SUMX2MY2());
        functions.put("SUMX2PY2", new SUMX2PY2());
        functions.put("SUMXMY2", new SUMXMY2());
        functions.put("SYD", new SYD());
        functions.put("T", new T());
        functions.put("TAN", new TAN());
        functions.put("TANH", new TANH());
        functions.put("TDIST", new TDIST());
        functions.put("TEXT", new TEXT());
        functions.put("TIME", new TIME());
        functions.put("TIMEVALUE", new TIMEVALUE());
        functions.put("TINV", new TINV());
        functions.put("TODAY", new TODAY());
        functions.put("TRANSPOSE", new TRANSPOSE());
        functions.put("TREND", new TREND());
        functions.put("TRIM", new TRIM());
        functions.put("TRIMMEAN", new TRIMMEAN());
        functions.put("TRUE", new TRUE());
        functions.put("TRUNC", new TRUNC());
        functions.put("TTEST", new TTEST());
        functions.put("TYPE", new TYPE());
        functions.put("UPPER", new UPPER());
        functions.put("VALUE", new VALUE());
        functions.put("VAR", new VAR());
        functions.put("VARA", new VARA());
        functions.put("VARP", new VARP());
        functions.put("VARPA", new VARPA());
        functions.put("VDB", new VDB());
        functions.put("VLOOKUP", new VLOOKUP());
        functions.put("WEEKDAY", new WEEKDAY());
        functions.put("WEIBULL", new WEIBULL());
        functions.put("YEAR", new YEAR());
        functions.put("ZTEST", new ZTEST());
        functions.put("VALOR", new VALUE());
        functions.put("SI", new IF());
        functions.put("NO", new NOT());
        functions.put("Y", new AND());
        functions.put("O", new OR());
        functions.put("FECHA", new DATE());
        functions.put("FECHAVALOR", new DATEVALUE());
        functions.put("DIA", new DAY());
        functions.put("MES", new MONTH());
        functions.put("ANIO", new YEAR());
        functions.put("ENTERO", new ROUNDDOWN());
        functions.put("TECHO", new ROUNDUP());
        functions.put("PISO", new ROUNDDOWN());
        functions.put("RESIDUO", new MOD());
        functions.put("REDONDEAR", new ROUND());
        functions.put("RAIZ", new SQRT());
        functions.put("HOY", new TODAY());
        functions.put("SUMARANIO", new ADDYEAR());
        functions.put("SUMARMES", new ADDMONTH());
    }
}
