INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('AFG', '2017-07-27 00:00:00', 'AFGANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ALB', '2017-07-27 00:00:00', 'ALBANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('DEU', '2017-07-27 00:00:00', 'ALEMANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('USA', '2017-07-27 00:00:00', 'AMERICANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('AND', '2017-07-27 00:00:00', 'ANDORRANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('AGO', '2017-07-27 00:00:00', 'ANGOLESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SAU', '2017-07-27 00:00:00', 'ARABE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('DZA', '2017-07-27 00:00:00', 'ARGELIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ARG', '2017-07-27 00:00:00', 'ARGENTINA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('AUS', '2017-07-27 00:00:00', 'AUSTRALIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('AUT', '2017-07-27 00:00:00', 'AUSTRIACA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BHS', '2017-07-27 00:00:00', 'BAHAMEÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BEL', '2017-07-27 00:00:00', 'BELGA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BLZ', '2017-07-27 00:00:00', 'BELICEÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BTN', '2017-07-27 00:00:00', 'BHUTANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BUR', '2017-07-27 00:00:00', 'BIRMANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BOL', '2017-07-27 00:00:00', 'BOLIVIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BWA', '2017-07-27 00:00:00', 'BOTSWANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BRA', '2017-07-27 00:00:00', 'BRASILEÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('VGB', '2017-07-27 00:00:00', 'BRITANICA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('IOT', '2017-07-27 00:00:00', 'BRITANICA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BGR', '2017-07-27 00:00:00', 'BULGARA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BFA', '2017-07-27 00:00:00', 'BURKINA FASO', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BDI', '2017-07-27 00:00:00', 'BURUNDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('KHM', '2017-07-27 00:00:00', 'CAMBOYANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CMR', '2017-07-27 00:00:00', 'CAMERUNESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CAN', '2017-07-27 00:00:00', 'CANADIENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CAF', '2017-07-27 00:00:00', 'CENTRO AFRICANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('TCD', '2017-07-27 00:00:00', 'CHADIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CSK', '2017-07-27 00:00:00', 'CHECOSLOVACA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CHL', '2017-07-27 00:00:00', 'CHILENA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CHN', '2017-07-27 00:00:00', 'CHINA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CYP', '2017-07-27 00:00:00', 'CHIPRIOTA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('COL', '2017-07-27 00:00:00', 'COLOMBIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('COM', '2017-07-27 00:00:00', 'COMORENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('COD', '2017-07-27 00:00:00', 'CONGOLESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CRI', '2017-07-27 00:00:00', 'COSTARRICENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CUB', '2017-07-27 00:00:00', 'CUBANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('DNK', '2017-07-27 00:00:00', 'DANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BHR', '2017-07-27 00:00:00', 'DE BAHREIN', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BRB', '2017-07-27 00:00:00', 'DE BARBADOS', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BEN', '2017-07-27 00:00:00', 'DE BENNIN', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CPV', '2017-07-27 00:00:00', 'DE CABO VERDE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('DJI', '2017-07-27 00:00:00', 'DE DJIBOUTI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('STP', '2017-07-27 00:00:00', 'DE SANTO TOME', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SYC', '2017-07-27 00:00:00', 'DE SEYCHELLES', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ZWE', '2017-07-27 00:00:00', 'DE ZIMBAWI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('QAT', '2017-07-27 00:00:00', 'DEL QATAR', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ESH', '2017-07-27 00:00:00', 'DEL SAHARA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('DMA', '2017-07-27 00:00:00', 'DOMINICA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('DOM', '2017-07-27 00:00:00', 'DOMINICANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('EGY', '2017-07-27 00:00:00', 'EGIPCIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SVK', '2017-07-27 00:00:00', 'ESLOVACA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('XES', '2017-07-27 00:00:00', 'ESLOVAQUIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SVN', '2017-07-27 00:00:00', 'ESLOVENIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ESP', '2017-07-27 00:00:00', 'ESPAÑOLA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('USA', '2017-07-27 00:00:00', 'ESTADOUNIDENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('EST', '2017-07-27 00:00:00', 'ESTONIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ETH', '2017-07-27 00:00:00', 'ETIOPE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('FJI', '2017-07-27 00:00:00', 'FIJIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PHL', '2017-07-27 00:00:00', 'FILIPINA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('FIN', '2017-07-27 00:00:00', 'FINLANDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('FRA', '2017-07-27 00:00:00', 'FRANCESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GAB', '2017-07-27 00:00:00', 'GABONESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GMB', '2017-07-27 00:00:00', 'GAMBIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GHA', '2017-07-27 00:00:00', 'GHANATA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('VCT', '2017-07-27 00:00:00', 'GRANADINA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GRC', '2017-07-27 00:00:00', 'GRIEGA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GTM', '2017-07-27 00:00:00', 'GUATEMALTECA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GNB', '2017-07-27 00:00:00', 'GUINEA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GIN', '2017-07-27 00:00:00', 'GUINEA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GNQ', '2017-07-27 00:00:00', 'GUINEA ECUATORIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GUY', '2017-07-27 00:00:00', 'GUYANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('HTI', '2017-07-27 00:00:00', 'HAITIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('IND', '2017-07-27 00:00:00', 'HINDU', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NLD', '2017-07-27 00:00:00', 'HOLANDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('HND', '2017-07-27 00:00:00', 'HONDUREÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('HUN', '2017-07-27 00:00:00', 'HUNGARA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('IDN', '2017-07-27 00:00:00', 'INDONESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('IRN', '2017-07-27 00:00:00', 'IRANI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('IRQ', '2017-07-27 00:00:00', 'IRAQUI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('IRL', '2017-07-27 00:00:00', 'IRLANDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ISL', '2017-07-27 00:00:00', 'ISLANDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ISR', '2017-07-27 00:00:00', 'ISRAELI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ITA', '2017-07-27 00:00:00', 'ITALIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('JAM', '2017-07-27 00:00:00', 'JAMAIQUINA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('JPN', '2017-07-27 00:00:00', 'JAPONESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('JOR', '2017-07-27 00:00:00', 'JORDANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('KEN', '2017-07-27 00:00:00', 'KENIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('KGZ', '2017-07-27 00:00:00', 'KIRGUISTAN', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('KWT', '2017-07-27 00:00:00', 'KUWAITI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LAO', '2017-07-27 00:00:00', 'LAOSIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LSO', '2017-07-27 00:00:00', 'LESOTHENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LBN', '2017-07-27 00:00:00', 'LIBANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LBR', '2017-07-27 00:00:00', 'LIBERIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LBY', '2017-07-27 00:00:00', 'LIBIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LIE', '2017-07-27 00:00:00', 'LIECHTENSTENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LTU', '2017-07-27 00:00:00', 'LITUANIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LUX', '2017-07-27 00:00:00', 'LUXEMBURGUESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MKD', '2017-07-27 00:00:00', 'MACEDONIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MYS', '2017-07-27 00:00:00', 'MALASIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MWI', '2017-07-27 00:00:00', 'MALAWIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MDV', '2017-07-27 00:00:00', 'MALDIVA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MLI', '2017-07-27 00:00:00', 'MALIENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MLT', '2017-07-27 00:00:00', 'MALTESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('COG', '2017-07-27 00:00:00', 'MARFILEÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MAR', '2017-07-27 00:00:00', 'MARROQUI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MUS', '2017-07-27 00:00:00', 'MAURICIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MRT', '2017-07-27 00:00:00', 'MAURITANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MEX', '2017-07-27 00:00:00', 'MEXICANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('FSM', '2017-07-27 00:00:00', 'MICRONECIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MDA', '2017-07-27 00:00:00', 'MOLDOVIA, REPUBLICA DE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MCO', '2017-07-27 00:00:00', 'MONEGASCA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MNG', '2017-07-27 00:00:00', 'MONGOLESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('MOZ', '2017-07-27 00:00:00', 'MOZAMBIQUEÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NAM', '2017-07-27 00:00:00', 'NAMIBIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NRU', '2017-07-27 00:00:00', 'NAURUANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NPL', '2017-07-27 00:00:00', 'NEPALESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NIC', '2017-07-27 00:00:00', 'NICARAGUENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NGA', '2017-07-27 00:00:00', 'NIGERIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NER', '2017-07-27 00:00:00', 'NIGERINA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PRK', '2017-07-27 00:00:00', 'NORCOREANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('NOR', '2017-07-27 00:00:00', 'NORUEGA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('VNM', '2017-07-27 00:00:00', 'NORVIETNAMITA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('OMN', '2017-07-27 00:00:00', 'OMANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PAK', '2017-07-27 00:00:00', 'PAKISTANI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PAN', '2017-07-27 00:00:00', 'PANAMEÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PNG', '2017-07-27 00:00:00', 'PAPUENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PRY', '2017-07-27 00:00:00', 'PARAGUAYA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PER', '2017-07-27 00:00:00', 'PERUANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PRT', '2017-07-27 00:00:00', 'PORTUGUESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('PRI', '2017-07-27 00:00:00', 'PUERTORRIQUEÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GBR', '2017-07-27 00:00:00', 'REINO UNIDO', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GBN', '2017-07-27 00:00:00', 'REINO UNIDO(BRIT. DEL EXT.)', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GBO', '2017-07-27 00:00:00', 'REINO UNIDO(C. BRIT. DEL EXT.)', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('GBD', '2017-07-27 00:00:00', 'REINO UNIDO(DEPEN. TET. BRIT.)', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ROM', '2017-07-27 00:00:00', 'RUMANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('RWA', '2017-07-27 00:00:00', 'RWANDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SLB', '2017-07-27 00:00:00', 'SALOMONESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SLV', '2017-07-27 00:00:00', 'SALVADOREÑA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('WSM', '2017-07-27 00:00:00', 'SAMOANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SMR', '2017-07-27 00:00:00', 'SAN MARINENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('LCA', '2017-07-27 00:00:00', 'SANTA LUCIENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SEN', '2017-07-27 00:00:00', 'SENEGALESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SLE', '2017-07-27 00:00:00', 'SIERRA LEONESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SGP', '2017-07-27 00:00:00', 'SINGAPORENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SYR', '2017-07-27 00:00:00', 'SIRIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SOM', '2017-07-27 00:00:00', 'SOMALI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('BLR', '2017-07-27 00:00:00', 'SOVIETICA BIELORRUSA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('UKR', '2017-07-27 00:00:00', 'SOVIETICA UCRANIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ZAF', '2017-07-27 00:00:00', 'SUDAFRICANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SDN', '2017-07-27 00:00:00', 'SUDANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('KOR', '2017-07-27 00:00:00', 'SUDCOREANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SWE', '2017-07-27 00:00:00', 'SUECA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('CHE', '2017-07-27 00:00:00', 'SUIZA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SUR', '2017-07-27 00:00:00', 'SURINAMENSE', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('SWZ', '2017-07-27 00:00:00', 'SWAZI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('THA', '2017-07-27 00:00:00', 'TAILANDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('TWN', '2017-07-27 00:00:00', 'TAIWANESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('TZA', '2017-07-27 00:00:00', 'TANZANIANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('TGO', '2017-07-27 00:00:00', 'TOGOLESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('TTO', '2017-07-27 00:00:00', 'TRINITARIA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('TUN', '2017-07-27 00:00:00', 'TUNECINA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('TUR', '2017-07-27 00:00:00', 'TURCA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('UGA', '2017-07-27 00:00:00', 'UGANDESA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('URY', '2017-07-27 00:00:00', 'URUGUAYA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('VAT', '2017-07-27 00:00:00', 'VATICANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('VEN', '2017-07-27 00:00:00', 'VENEZOLANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('YEM', '2017-07-27 00:00:00', 'YEMENI', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('YUG', '2017-07-27 00:00:00', 'YUGOSLAVA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ZAR', '2017-07-27 00:00:00', 'ZAIRANA', 14, 'atk', 1);
INSERT INTO sch_proteus.catalogo (codigo, fecha_creacion, nombre, id_tipocatalogo, usuario_creacion, vigente) VALUES ('ZMB', '2017-07-27 00:00:00', 'ZAMBIANA', 14, 'atk', 1);

