/*
 *  ReportesEnum.java
 *  Proteus V 2.0 $Revision 1.0 $
 *
 *  Todos los derechos reservados. All rights reserved.
 *  This software is the confidential and proprietary information of Proteus
 *  ("Confidential Information").  You shall not disclose such Confidential
 *  Information and shall use it only in accordance with the terms of the
 *  license agreement you entered into
 *  with Proteus.
 *
 *  Proteus
 *  Quito - Ecuador
 *  
 *
 *  12/11/2012
 *
 */
package ec.com.atikasoft.proteus.enums;

/**
 *
 * @author Alvaro Tituaña <alvaro.tituania@marcasoft.ec>
 */
public enum ReportesEnum {

    /**
     * VARIABLE DE REPORTE PARA DETALLE DE HORARIOS.
     */
    DETALLE_HORARIOS("PROTEUS_DETALLE_HORARIOS"),
    /**
     * VARIABLE DE REPORTE PARA LA NUEVA SOLICITUD.
     */
    SOLICITUD_LP("PROTEUS_SOLICITUD_LP"),
    /**
     * VARIABLE DE REPORTE PARA REQUISITOS.
     */
    CLASES("PROTEUS_CLASE"),
    /**
     * VARIABLE DE REPORTE PARA REQUISITOS.
     */
    REQUISITOS("PROTEUS_REQUISITO"),
    /**
     * VARIABLE DE REPORTE PARA EJERCICIOS FOSCALES.
     */
    EJERCICIOS_FISCALES("PROTEUS_EJERCICIO_FISCAL"),
    /**
     * VARIABLE DE REPORTE PARA REQUISITOS POR TIPÓS DE MOVIMIENTOS.
     */
    TIPOS_MOVIMIENTOS_REQUISITOS("PROTEUS_TIPO_MOVIMIENTO_REQUISITO"),
    /**
     * VARIABLE DE REPORTE PARA ALERTAS POR TIPÓS DE MOVIMIENTOS.
     */
    TIPOS_MOVIMIENTOS_ALERTAS("PROTEUS_TIPO_MOVIMIENTO_ALERTA"),
    /**
     * VARIABLE DE REPORTE PARA REGLAS POR TIPÓS DE MOVIMIENTOS.
     */
    TIPOS_MOVIMIENTOS_REGLAS("PROTEUS_TIPO_MOVIMIENTO_REGLA"),
    /**
     * VARIABLE DE REPORTE PARA TIPÓS DE MOVIMIENTOS.
     */
    TIPOS_MOVIMIENTOS("PROTEUS_TIPO_MOVIMIENTO"),
    /**
     * VARIABLE DE REPORTE PARA GRUPOS.
     */
    GRUPOS("PROTEUS_GRUPO"),
    /**
     * VARIABLE DE REPORTE PARA UN DOCUMENTO HABILITANTE.
     */
    DOCUMENTOS_HABILITANTES("PROTEUS_DOCUMENTO_HABILITANTE"),
    /**
     * VARIABLE DE REPORTE PARA UNA ALERTA.
     */
    ALERTAS("PROTEUS_ALERTA"),
    /**
     * VARIABLE DE REPORTE PARA ACCION DE PERSONAL VISTA PREVIA.
     */
    ACCIONES_PERSONAL("PROTEUS_ACCION_PERSONAL"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATOS SERVICIOS OCACIONALES VISTA PREVIA.
     */
    CONTRATO_SERVICIOS_OCASIONALES("PROTEUS_CONTRATO_SERVICIOS_OCACIONALES"),
    /**
     * VARIABLE DE REPORTE PARA ACCION DE PERSONAL IMPRESION.
     */
    ACCIONES_PERSONAL_IMPR("PROTEUS_ACCION_PERSONAL_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATOS SERVICIOS OCACIONALES IMPRESION.
     */
    CONTRATO_SERVICIOS_OCASIONALES_IMPR("PROTEUS_CONTRATO_SERVICIOS_OCACIONALES_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA MEMORANDO VISTA PREVIA.
     */
    MEMORANDO_VISTA_PREVIA("PROTEUS_MEMORANDO_VP"),
    /**
     * VARIABLE DE REPORTE PARA MEMORANDO IMPRESION.
     */
    MEMORANDO_IMPRESION("PROTEUS_MEMORANDO_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA UNA REGLA.
     */
    REGLAS("PROTEUS_REGLA"),
    /**
     * VARIABLE DE REPORTE PARA UNA NOMINA.
     */
    NOMINA("PROTEUS_NOMINA"),
    /**
     * VARIABLE DE REPORTE PARA UNA NOMINA.
     */
    TOTAL_NOMINA("PROTEUS_TOTAL_NOMINAS"),
    /**
     * VARIABLE DE REPORTE PARA CONSULTA DE HISTORIAL DE MOVIMIENTOS DE
     * SERVIDOR.
     */
    CONSULTA_HISTORIAL_MOVIMIENTOS_SERVIDOR("PROTEUS_HISTORIAL_MOVIMIENTOS_SERVIDOR"),
    /**
     * VARIABLE DE REPORTE PARA CONSULTA DE MOVIMIENTOS POR ANALISTA.
     */
    CONSULTA_MOVIMIENTOS_ANALISTA("PROTEUS_CONSULTA_MOVIMIENTOS_ANALISTA"),
    /**
     * VARIABLE DE REPORTE PARA CONSULTA VACACIONES.
     */
    CONSULTA_SOLICITUD_VACACIONES("PROTEUS_SOLICITUD_VACACIONES"),
    /**
     * VARIABLE DE REPORTE PARA PERMISOS CON CARGO A VACACIONES.
     */
    CONSULTA_SOLICITUD_PERMISO_CARGO_VACACIONES("PROTEUS_PERMISO_HORAS"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO A PLAZO FIJO.
     */
    CONTRATO_TRABAJO_PLAZO_FIJO("PROTEUS_CONTRATO_TRABAJO_PLAZO_FIJO"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO A PLAZO FIJO.
     */
    CONTRATO_TRABAJO_PLAZO_FIJO_IMPR("PROTEUS_CONTRATO_TRABAJO_PLAZO_FIJO_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO EVENTUAL.
     */
    CONTRATO_TRABAJO_EVENTUAL("PROTEUS_CONTRATO_TRABAJO_EVENTUAL"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO EVENTUAL.
     */
    CONTRATO_TRABAJO_EVENTUAL_IMPR("PROTEUS_CONTRATO_TRABAJO_EVENTUAL_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO POR TIEMPO INDEFINIDO CON
     * PERIDODO DE PRUEBA.
     */
    CONTRATO_TRABAJO_INDEFINIDO_PRUEBA("PROTEUS_CONTRATO_TRABAJO_INDEFINIDO_PRUEBA"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO POR TIEMPO INDEFINIDO CON
     * PERIDODO DE PRUEBA.
     */
    CONTRATO_TRABAJO_INDEFINIDO_PRUEBA_IMPR("PROTEUS_CONTRATO_TRABAJO_INDEFINIDO_PRUEBA_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TEMPORADA.
     */
    CONTRATO_TRABAJO_TEMPORADA("PROTEUS_CONTRATO_TRABAJO_TEMPORADA"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TEMPORADA.
     */
    CONTRATO_TRABAJO_TEMPORADA_IMPR("PROTEUS_CONTRATO_TRABAJO_TEMPORADA_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO_TIEMPO_INDEFINIDO("PROTEUS_CONTRATO_TRABAJO_TIEMPO_INDEFINIDO"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO_TIEMPO_INDEFINIDO_IMPR("PROTEUS_CONTRATO_TRABAJO_TIEMPO_INDEFINIDO_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO_PLAZO_FIJO_PERIODO_DE_PRUEBA("PROTEUS_CONTRATO_TRABAJO_PLAZO_FIJO_PERIODO_DE_PRUEBA"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO_PLAZO_FIJO_PERIODO_DE_PRUEBA_IMPR("PROTEUS_CONTRATO_TRABAJO_PLAZO_FIJO_PERIODO_DE_PRUEBA_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO_PLAZO_FIJO_JORNADA_PARCIAL("PROTEUS_CONTRATO_TRABAJO_PLAZO_FIJO_JORNADA_PARCIAL"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO_PLAZO_FIJO_JORNADA_PARCIAL_IMPR("PROTEUS_CONTRATO_TRABAJO_PLAZO_FIJO_JORNADA_PARCIAL_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO_IMPR("PROTEUS_CONTRATO_TRABAJO_IMPR"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE SOLICITUD_ANTICIPO.
     */
    SOLICITUD_ANTICIPO("PROTEUS_SOLICITUD_ANTICIPO"),
    /**
     * VARIABLE DE REPORTE PARA CONTRATO DE TRABAJO TIEMPO INDEFINIDO.
     */
    CONTRATO_TRABAJO("PROTEUS_CONTRATO_TRABAJO"),
    /**
     * Resumen rol de pagos.
     */
    PROTEUS_RESUMEN_ROL_DE_PAGOS("PROTEUS_RESUMEN_ROL_DE_PAGOS"),
    /**
     * CONSULTA NOMINAS.
     */
    PROTEUS_CONSULTA_NOMINA("PROTEUS_CONSULTA_NOMINA"),
    /**
     * Resumen ingresos descuentos.
     */
    PROTEUS_RESUMEN_POR_INGRESOS_DESCUENTOS("PROTEUS_RESUMEN_POR_INGRESOS_DESCUENTOS"),
    /**
     * Resumen ingresos descuentos.
     */
    //PROTEUS_RESUMEN_ROL_DE_PAGOS_POR_UNIDAD_ORG("PROTEUS_RESUMEN_ROL_DE_PAGOS_POR_UNIDAD_ORG"),
    /**
     * resumen pagos por direccion.
     */
    PROTEUS_RESUMEN_DE_PAGOS_POR_DIRECCIONES("PROTEUS_RESUMEN_DE_PAGOS_POR_DIRECCIONES"),
    /**
     * resumen de retencion.
     */
    PROTEUS_RESUMEN_DE_RETENCIONES("PROTEUS_RESUMEN_DE_RETENCIONES"),
    /**
     * Resumen de descuentos.
     */
    PROTEUS_RESUMEN_DE_DESCUENTOS("PROTEUS_RESUMEN_DE_DESCUENTOS"),
    /**
     * Acta terminacion de contrato servicio ocacionales.
     */
    PROTEUS_ACTA_TERMINACION_CONTRATO_SERVICIOS_OCACIONALES("PROTEUS_ACTA_DE_TERMINACION_DE_CONTRATO"),
    /**
     * Confidencial de pagos.
     */
    PROTEUS_CONFIDENCIAL_PAGO("PROTEUS_CONFIDENCIAL_PAGO"),
    /**
     * Acta terminacion de contrato servicio ocacionales.
     */
    PROTEUS_ADEMDUM_MODIFICATORIO_CAMBIO_DEPENDENCIA("PROTEUS_ADEMDUM_MODIFICATORIO_CAMBIO_DEPENDENCIA"),
    /**
     * Resumen por rubros.
     */
    PROTEUS_RESUMEN_POR_RUBROS("PROTEUS_RESUMEN_POR_RUBROS"),
    /**
     * Formulario 107.
     */
    PROTEUS_FORMULARIO_107("PROTEUS_FORMULARIO_107"),
    /**
     * IMPUESTO A LA RENTA POR PERIODOS.
     */
    PROTEUS_IMPUESTO_RENTA_PERIODO("PROTEUS_IMPUESTO_RENTA_PERIODO"),
    /**
     * FORMULARIO GASTOS PERSONALES.
     */
    PROTEUS_GASTOS_PERSONALES("PROTEUS_GASTOS_PERSONALES"),
    /**
     * CONSULTA TRAYECTORIA LABORAL
     */
    PROTEUS_CONSULTA_TRAYECTORIA_LABORAL("PROTEUS_CONSULTA_TRAYECTORIA_LABORAL"),
    /**
     * Reporte de Novedades
     */
    PROTEUS_REPORTE_NOVEDADES("PROTEUS_NOVEDADES"),
    /**
     * Reporte FORMULARIO 107
     */
    PROTEUS_REPORTE_FORMULARIO_107("PROTEUS_GASTOS_PERSONALES_107")
    ;

    /**
     * Codigo de la enumeracion.
     */
    private String reporte;

    /**
     * Constructor.
     *
     * @param reporte String
     */
    private ReportesEnum(final String reporte) {
        this.reporte = reporte;
    }

    /**
     * @return the reporte
     */
    public String getReporte() {
        return reporte;
    }

    /**
     * @param reporte the reporte to set
     */
    public void setReporte(final String reporte) {
        this.reporte = reporte;
    }
}
